name: TreeLearn
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
channel_priority: flexible

dependencies:
  - python=3.10
  - pip

  # --- PyTorch + CUDA 11.8
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8  

  # --- science computing libraries ---
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pillow
  - networkx
  - sympy
  - requests
  - jinja2
  - tensorboard
  - tensorboardx
  - svgwrite
  - packaging
  - typing_extensions

  - pip:
      - chardet==5.2.0
      - cython==0.29.37
      - lxml==5.3.2
      - path==17.1.0
      - pyglet==1.5.31
      - trimesh==3.23.5

      # The following packages are optional and may require additional setup.
      # - pyembree==0.1.12
      # - python-fcl==0.7.0.8
