dataset_test:
  training: False # True if dataset used for training; False if used for validation
  data_root: 'data/val/tiles/npz' # folder where tiles for model validation are located
  inner_square_edge_length: 8 # Length of inner square to be used for validation. E.g. if tiles are 30mx30m, this indicates that only inner 8x8 is taken into account (see paper for details)
  